services:
  db:
    image: postgres:16
    container_name: potentiel_dashboard_db
    environment:
      - POSTGRES_USER=metabase
      - POSTGRES_PASSWORD=password
    restart: always
    ports:
      - 5432:5432
  metabase:
    image: metabase/metabase:v0.53.3
    container_name: metabase
    ports:
      - 3001:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: password
      MB_DB_HOST: db
    depends_on:
    - db
  app:
    build: .
    ports: 
      - 3000:3000
    environment:
      - NODE_ENV=production
      - METABASE_URL=${METABASE_URL}
      - METABASE_SECRET=${METABASE_SECRET}
      - METABASE_DASHBOARD_ID=${METABASE_DASHBOARD_ID}
    depends_on:
      - metabase